### ISSUE TITLE
我觉得像redis

### ISSUE THREAD

**Issue by jjggzz** [likowong/simple-development#1]

**Comment by jjggzz** [comment]
我觉得redis和mongo这种组件应该要支持集群和单节点的自定义配置，不然不好用

**Comment by likowong** [comment]
肯定啊，这是基础版本而已发自我的华为手机-------- 原始邮件 --------发件人： jjggzz <notifications@github.com>日期： 2020年11月23日周一 11:08收件人： likowong/simple-development <simple-development@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [likowong/simple-development] 王哥又拾起了梦想୧(๑•̀◡•́๑)૭ (#1)

我觉得redis和mongo这种组件应该要支持集群和单节点的自定义配置，不然不好用
